name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      image: postgres:alpine
      container_name: db
      ports:
        - 5444:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build --console=plain

      - name: Run unit tests
        run: ./gradlew test --console=plain
